#PULLING OFFICIAL NODE IMAGE FROM DOCKER 
FROM node:12.7.0-alpine

#SETTING WORKING DIRECTORY TO /APP
WORKDIR /usr/src/app

#COPYING PACKAGE.JSON FILE  TO WORKING DIRECTORY
COPY package*.json ./

#INSTALLING NEEDED PACKAGES 
RUN npm install

#COPY CODE/FILES TO WORKING DIRECTORY
COPY . .

#EXPOSING PORT 5001 TO BE PUBLICLY ACCESSIBLE
EXPOSE 5001

#RUNNING INDEX.JS WHEN CONTAINER LAUNCHES
CMD [ "node", "index.js" ]